In [38]:
import pandas as pd
import numpy as np
## Import Confusion matrix, plot confusion matrix, classification report, accuracy score, auc-roc score and roc curve
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
## Import Label encoder, label binarizer and Standard Scaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

## ================================ ##

from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
import warnings
warnings.filterwarnings("ignore")

In [39]:
df = pd.read_csv("stress_dataset.csv")
df.head()

Person ID Gender  Age            Occupation  Sleep Duration  \
0          1   Male   27     Software Engineer             6.1   
1          2   Male   28                Doctor             6.2   
2          3   Male   28                Doctor             6.2   
3          4   Male   28  Sales Representative             5.9   
4          5   Male   28  Sales Representative             5.9   

   Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                 6                       42             6   Overweight   
1                 6                       60             8       Normal   
2                 6                       60             8       Normal   
3                 4                       30             8        Obese   
4                 4                       30             8        Obese   

  Blood Pressure  Heart Rate  Daily Steps Sleep Disorder  
0         126/83          77         4200            NaN  
1         125/80          75        10000            NaN  
2         125/80          75        10000            NaN  
3         140/90          85         3000    Sleep Apnea  
4         140/90          85         3000    Sleep Apnea

In [41]:
df=df.drop(columns=['Sleep Disorder'],axis=1)

# **Exploratory Data Analysis**

In [42]:
df.columns

Index(['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Quality of Sleep', 'Physical Activity Level', 'Stress Level',
       'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps'],
      dtype='object')

In [4]:
df.shape

(374, 13)

In [5]:
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [6]:
df['Occupation'].unique()

array(['Software Engineer', 'Doctor', 'Sales Representative', 'Teacher',
       'Nurse', 'Engineer', 'Accountant', 'Scientist', 'Lawyer',
       'Salesperson', 'Manager'], dtype=object)

In [7]:
df['BMI Category'].unique()

array(['Overweight', 'Normal', 'Obese', 'Normal Weight'], dtype=object)

In [8]:
dict1= {"Normal Weight": 0,
        'Overweight': 1,
        'Normal': 0,
        'Obese': 2
}
df['BMI Category']=df['BMI Category'].map(dict1)
df

Person ID  Gender  Age            Occupation  Sleep Duration  \
0            1    Male   27     Software Engineer             6.1   
1            2    Male   28                Doctor             6.2   
2            3    Male   28                Doctor             6.2   
3            4    Male   28  Sales Representative             5.9   
4            5    Male   28  Sales Representative             5.9   
..         ...     ...  ...                   ...             ...   
369        370  Female   59                 Nurse             8.1   
370        371  Female   59                 Nurse             8.0   
371        372  Female   59                 Nurse             8.1   
372        373  Female   59                 Nurse             8.1   
373        374  Female   59                 Nurse             8.1   

     Quality of Sleep  Physical Activity Level  Stress Level  BMI Category  \
0                   6                       42             6             1   
1                   6                       60             8             0   
2                   6                       60             8             0   
3                   4                       30             8             2   
4                   4                       30             8             2   
..                ...                      ...           ...           ...   
369                 9                       75             3             1   
370                 9                       75             3             1   
371                 9                       75             3             1   
372                 9                       75             3             1   
373                 9                       75             3             1   

    Blood Pressure  Heart Rate  Daily Steps Sleep Disorder  
0           126/83          77         4200            NaN  
1           125/80          75        10000            NaN  
2           125/80          75        10000            NaN  
3           140/90          85         3000    Sleep Apnea  
4           140/90          85         3000    Sleep Apnea  
..             ...         ...          ...            ...  
369         140/95          68         7000    Sleep Apnea  
370         140/95          68         7000    Sleep Apnea  
371         140/95          68         7000    Sleep Apnea  
372         140/95          68         7000    Sleep Apnea  
373         140/95          68         7000    Sleep Apnea  

[374 rows x 13 columns]

In [9]:
x=df[['Occupation','Stress Level']].copy()
x

Occupation  Stress Level
0       Software Engineer             6
1                  Doctor             8
2                  Doctor             8
3    Sales Representative             8
4    Sales Representative             8
..                    ...           ...
369                 Nurse             3
370                 Nurse             3
371                 Nurse             3
372                 Nurse             3
373                 Nurse             3

[374 rows x 2 columns]

# **Data Preprocessing**

In [12]:
df["Stress Level"].unique()

array([6, 8, 7, 4, 3, 5], dtype=int64)

In [13]:
str = df.loc[:, 'Stress Level']

str[ str<4 ] = 0
str[ (3<str) & (str<=6) ] = 1
str[ (6<str) & (str<=10) ] = 2

In [14]:
df

Person ID  Gender  Age            Occupation  Sleep Duration  \
0            1    Male   27     Software Engineer             6.1   
1            2    Male   28                Doctor             6.2   
2            3    Male   28                Doctor             6.2   
3            4    Male   28  Sales Representative             5.9   
4            5    Male   28  Sales Representative             5.9   
..         ...     ...  ...                   ...             ...   
369        370  Female   59                 Nurse             8.1   
370        371  Female   59                 Nurse             8.0   
371        372  Female   59                 Nurse             8.1   
372        373  Female   59                 Nurse             8.1   
373        374  Female   59                 Nurse             8.1   

     Quality of Sleep  Physical Activity Level  Stress Level  BMI Category  \
0                   6                       42             1             1   
1                   6                       60             2             0   
2                   6                       60             2             0   
3                   4                       30             2             2   
4                   4                       30             2             2   
..                ...                      ...           ...           ...   
369                 9                       75             0             1   
370                 9                       75             0             1   
371                 9                       75             0             1   
372                 9                       75             0             1   
373                 9                       75             0             1   

    Blood Pressure  Heart Rate  Daily Steps Sleep Disorder  
0           126/83          77         4200            NaN  
1           125/80          75        10000            NaN  
2           125/80          75        10000            NaN  
3           140/90          85         3000    Sleep Apnea  
4           140/90          85         3000    Sleep Apnea  
..             ...         ...          ...            ...  
369         140/95          68         7000    Sleep Apnea  
370         140/95          68         7000    Sleep Apnea  
371         140/95          68         7000    Sleep Apnea  
372         140/95          68         7000    Sleep Apnea  
373         140/95          68         7000    Sleep Apnea  

[374 rows x 13 columns]

In [15]:
df=pd.get_dummies(df, columns=["Occupation"],dtype=int)
dict={"Male":1,
         "Female":0
       }
df['Gender']=df['Gender'].map(dict)
df.head()

Person ID  Gender  Age  Sleep Duration  Quality of Sleep  \
0          1       1   27             6.1                 6   
1          2       1   28             6.2                 6   
2          3       1   28             6.2                 6   
3          4       1   28             5.9                 4   
4          5       1   28             5.9                 4   

   Physical Activity Level  Stress Level  BMI Category Blood Pressure  \
0                       42             1             1         126/83   
1                       60             2             0         125/80   
2                       60             2             0         125/80   
3                       30             2             2         140/90   
4                       30             2             2         140/90   

   Heart Rate  ...  Occupation_Doctor Occupation_Engineer  Occupation_Lawyer  \
0          77  ...                  0                   0                  0   
1          75  ...                  1                   0                  0   
2          75  ...                  1                   0                  0   
3          85  ...                  0                   0                  0   
4          85  ...                  0                   0                  0   

   Occupation_Manager  Occupation_Nurse  Occupation_Sales Representative  \
0                   0                 0                                0   
1                   0                 0                                0   
2                   0                 0                                0   
3                   0                 0                                1   
4                   0                 0                                1   

   Occupation_Salesperson  Occupation_Scientist  Occupation_Software Engineer  \
0                       0                     0                             1   
1                       0                     0                             0   
2                       0                     0                             0   
3                       0                     0                             0   
4                       0                     0                             0   

   Occupation_Teacher  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 23 columns]

In [18]:
df[['Systolic Pressure', 'Diastolic Pressure']] = df['Blood Pressure'].str.split('/', expand = True)

In [19]:
df

Person ID  Gender  Age  Sleep Duration  Quality of Sleep  \
0            1       1   27             6.1                 6   
1            2       1   28             6.2                 6   
2            3       1   28             6.2                 6   
3            4       1   28             5.9                 4   
4            5       1   28             5.9                 4   
..         ...     ...  ...             ...               ...   
369        370       0   59             8.1                 9   
370        371       0   59             8.0                 9   
371        372       0   59             8.1                 9   
372        373       0   59             8.1                 9   
373        374       0   59             8.1                 9   

     Physical Activity Level  Stress Level  BMI Category Blood Pressure  \
0                         42             1             1         126/83   
1                         60             2             0         125/80   
2                         60             2             0         125/80   
3                         30             2             2         140/90   
4                         30             2             2         140/90   
..                       ...           ...           ...            ...   
369                       75             0             1         140/95   
370                       75             0             1         140/95   
371                       75             0             1         140/95   
372                       75             0             1         140/95   
373                       75             0             1         140/95   

     Heart Rate  ...  Occupation_Nurse  Occupation_Sales Representative  \
0            77  ...                 0                                0   
1            75  ...                 0                                0   
2            75  ...                 0                                0   
3            85  ...                 0                                1   
4            85  ...                 0                                1   
..          ...  ...               ...                              ...   
369          68  ...                 1                                0   
370          68  ...                 1                                0   
371          68  ...                 1                                0   
372          68  ...                 1                                0   
373          68  ...                 1                                0   

     Occupation_Salesperson  Occupation_Scientist  \
0                         0                     0   
1                         0                     0   
2                         0                     0   
3                         0                     0   
4                         0                     0   
..                      ...                   ...   
369                       0                     0   
370                       0                     0   
371                       0                     0   
372                       0                     0   
373                       0                     0   

     Occupation_Software Engineer  Occupation_Teacher  \
0                               1                   0   
1                               0                   0   
2                               0                   0   
3                               0                   0   
4                               0                   0   
..                            ...                 ...   
369                             0                   0   
370                             0                   0   
371                             0                   0   
372                             0                   0   
373                             0                   0   

     Sleep Disorder_Insomnia  Sleep Disorder_Sleep Apnea  Systolic Pressure  \
0                    

In [20]:
df=df.drop(columns=['Blood Pressure'],axis=1)
df

Person ID  Gender  Age  Sleep Duration  Quality of Sleep  \
0            1       1   27             6.1                 6   
1            2       1   28             6.2                 6   
2            3       1   28             6.2                 6   
3            4       1   28             5.9                 4   
4            5       1   28             5.9                 4   
..         ...     ...  ...             ...               ...   
369        370       0   59             8.1                 9   
370        371       0   59             8.0                 9   
371        372       0   59             8.1                 9   
372        373       0   59             8.1                 9   
373        374       0   59             8.1                 9   

     Physical Activity Level  Stress Level  BMI Category  Heart Rate  \
0                         42             1             1          77   
1                         60             2             0          75   
2                         60             2             0          75   
3                         30             2             2          85   
4                         30             2             2          85   
..                       ...           ...           ...         ...   
369                       75             0             1          68   
370                       75             0             1          68   
371                       75             0             1          68   
372                       75             0             1          68   
373                       75             0             1          68   

     Daily Steps  ...  Occupation_Nurse  Occupation_Sales Representative  \
0           4200  ...                 0                                0   
1          10000  ...                 0                                0   
2          10000  ...                 0                                0   
3           3000  ...                 0                                1   
4           3000  ...                 0                                1   
..           ...  ...               ...                              ...   
369         7000  ...                 1                                0   
370         7000  ...                 1                                0   
371         7000  ...                 1                                0   
372         7000  ...                 1                                0   
373         7000  ...                 1                                0   

     Occupation_Salesperson  Occupation_Scientist  \
0                         0                     0   
1                         0                     0   
2                         0                     0   
3                         0                     0   
4                         0                     0   
..                      ...                   ...   
369                       0                     0   
370                       0                     0   
371                       0                     0   
372                       0                     0   
373                       0                     0   

     Occupation_Software Engineer  Occupation_Teacher  \
0                               1                   0   
1                               0                   0   
2                               0                   0   
3                               0                   0   
4                               0                   0   
..                            ...                 ...   
369                             0                   0   
370                             0                   0   
371                             0                   0   
372                             0                   0   
373                             0                   0   

     Sleep Disorder_Insomnia  Sleep Disorder_Sleep Apnea  Systolic Pressure  \
0                          0                 

In [21]:
df['Stress Level'].unique()

array([1, 2, 0], dtype=int64)

In [23]:
df.columns

Index(['Person ID', 'Gender', 'Age', 'Sleep Duration', 'Quality of Sleep',
       'Physical Activity Level', 'Stress Level', 'BMI Category', 'Heart Rate',
       'Daily Steps', 'Occupation_Accountant', 'Occupation_Doctor',
       'Occupation_Engineer', 'Occupation_Lawyer', 'Occupation_Manager',
       'Occupation_Nurse', 'Occupation_Sales Representative',
       'Occupation_Scientist', 'Occupation_Software Engineer',
       'Occupation_Teacher', 'Systolic Pressure', 'Diastolic Pressure'],
      dtype='object')

In [24]:
X = df.drop(columns=['Stress Level'],axis=1)
y = df['Stress Level']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)

In [25]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

# **MODELS**

# XGBoost Classifier

In [26]:
from xgboost.sklearn import XGBClassifier

xg_clf = XGBClassifier(n_estimators=500,learning_rate=0.05,max_depth=1)
xg_clf.fit(X_train_scaled, y_train)
print(xg_clf)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=1, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=500, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)


In [27]:
def print_score_details(clf, X_train_scaled, y_train, X_test_scaled, y_test):
        pred = clf.predict(X_test_scaled)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n")        
        print("Accuracy Score:",accuracy_score(y_test, pred),"\n")
        print("Classification Report:\n",clf_report,"\n")
        print("Confusion Matrix:\n",confusion_matrix(y_test, pred),"\n")

In [28]:
print_score_details(xg_clf, X_train_scaled, y_train, X_test_scaled, y_test)

Test Result:

Accuracy Score: 0.9866666666666667 

Classification Report:
               0          1          2  accuracy   macro avg  weighted avg
precision   1.0   0.984375   0.982759  0.986667    0.989045      0.986667
recall      1.0   0.984375   0.982759  0.986667    0.989045      0.986667
f1-score    1.0   0.984375   0.982759  0.986667    0.989045      0.986667
support    28.0  64.000000  58.000000  0.986667  150.000000    150.000000 

Confusion Matrix:
 [[28  0  0]
 [ 0 63  1]
 [ 0  1 57]] 



In [29]:
pred3 = xg_clf.predict(X_train_scaled)
clf_report = pd.DataFrame(classification_report(y_train, pred3, output_dict=True))
print("Train Result:\n")        
print("Accuracy Score:",accuracy_score(y_train, pred3),"\n")
print("Classification Report:\n",clf_report,"\n")
print("Confusion Matrix:\n",confusion_matrix(y_train, pred3),"\n")

Train Result:

Accuracy Score: 0.9955357142857143 

Classification Report:
               0           1          2  accuracy   macro avg  weighted avg
precision   1.0    1.000000   0.984127  0.995536    0.994709      0.995607
recall      1.0    0.991597   1.000000  0.995536    0.997199      0.995536
f1-score    1.0    0.995781   0.992000  0.995536    0.995927      0.995544
support    43.0  119.000000  62.000000  0.995536  224.000000    224.000000 

Confusion Matrix:
 [[ 43   0   0]
 [  0 118   1]
 [  0   0  62]] 



**Hyperparameter Tuning**

In [31]:
xg_grid = {
    "learning_rate":[0.01, 0.05, 0.1],
    "n_estimators":[100,500,1000],
    "max_depth":[5,10]
}
xg_clf = XGBClassifier()

xg_cv = RandomizedSearchCV(
    xg_clf, 
    xg_grid,
    scoring="f1",
    n_iter=20,
    cv=5
)

xg_cv.fit(X_train_scaled, y_train)
xg_best_params = xg_cv.best_params_
xg_clf = XGBClassifier(**xg_best_params)
xg_clf.fit(X_train_scaled, y_train)
print("Best paramters: ",xg_best_params,"\n")

Best paramters:  {'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.01} 



In [32]:
print_score_details(xg_clf, X_train_scaled, y_train, X_test_scaled, y_test)

Test Result:

Accuracy Score: 0.9866666666666667 

Classification Report:
               0          1          2  accuracy   macro avg  weighted avg
precision   1.0   1.000000   0.966667  0.986667    0.988889      0.987111
recall      1.0   0.968750   1.000000  0.986667    0.989583      0.986667
f1-score    1.0   0.984127   0.983051  0.986667    0.989059      0.986674
support    28.0  64.000000  58.000000  0.986667  150.000000    150.000000 

Confusion Matrix:
 [[28  0  0]
 [ 0 62  2]
 [ 0  0 58]] 



In [33]:
pred3 = xg_clf.predict(X_train_scaled)
clf_report = pd.DataFrame(classification_report(y_train, pred3, output_dict=True))
print("Train Result:\n")        
print("Accuracy Score:",accuracy_score(y_train, pred3),"\n")
print("Classification Report:\n",clf_report,"\n")
print("Confusion Matrix:\n",confusion_matrix(y_train, pred3),"\n")

Train Result:

Accuracy Score: 0.9910714285714286 

Classification Report:
                    0           1     2  accuracy   macro avg  weighted avg
precision   1.000000    0.983471   1.0  0.991071    0.994490      0.991219
recall      0.953488    1.000000   1.0  0.991071    0.984496      0.991071
f1-score    0.976190    0.991667   1.0  0.991071    0.989286      0.991002
support    43.000000  119.000000  62.0  0.991071  224.000000    224.000000 

Confusion Matrix:
 [[ 41   2   0]
 [  0 119   0]
 [  0   0  62]] 



# Decision Tree Classifier

In [34]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(random_state=24)
tree_clf.fit(X_train_scaled, y_train)
print_score_details(tree_clf, X_train_scaled, y_train, X_test_scaled, y_test)

Test Result:

Accuracy Score: 0.9533333333333334 

Classification Report:
               0          1          2  accuracy   macro avg  weighted avg
precision   1.0   0.913043   0.981132  0.953333    0.964725      0.955603
recall      1.0   0.984375   0.896552  0.953333    0.960309      0.953333
f1-score    1.0   0.947368   0.936937  0.953333    0.961435      0.953159
support    28.0  64.000000  58.000000  0.953333  150.000000    150.000000 

Confusion Matrix:
 [[28  0  0]
 [ 0 63  1]
 [ 0  6 52]] 



In [35]:
pred3 = tree_clf.predict(X_train_scaled)
clf_report = pd.DataFrame(classification_report(y_train, pred3, output_dict=True))
print("Train Result:\n")        
print("Accuracy Score:",accuracy_score(y_train, pred3),"\n")
print("Classification Report:\n",clf_report,"\n")
print("Confusion Matrix:\n",confusion_matrix(y_train, pred3),"\n")

Train Result:

Accuracy Score: 1.0 

Classification Report:
               0      1     2  accuracy  macro avg  weighted avg
precision   1.0    1.0   1.0       1.0        1.0           1.0
recall      1.0    1.0   1.0       1.0        1.0           1.0
f1-score    1.0    1.0   1.0       1.0        1.0           1.0
support    43.0  119.0  62.0       1.0      224.0         224.0 

Confusion Matrix:
 [[ 43   0   0]
 [  0 119   0]
 [  0   0  62]] 



**The model seems overfit**

In [45]:
from sklearn.model_selection import GridSearchCV

params = {
    "criterion":("gini","entropy"), 
    "splitter":("best", "random"), 
    "min_samples_split":[10,20,30] 
}


tree_cv = GridSearchCV(
    tree_clf, 
    params, 
    scoring="f1", 
    cv=5
) 

tree_cv.fit(X_train_scaled, y_train)
best_params = tree_cv.best_params_
print("Best paramters: ",best_params,"\n")

tree_clf = DecisionTreeClassifier(**best_params)
tree_clf.fit(X_train_scaled, y_train)
print_score_details(tree_clf, X_train_scaled, y_train, X_test_scaled, y_test)


Best paramters:  {'criterion': 'gini', 'min_samples_split': 10, 'splitter': 'best'} 

Test Result:

Accuracy Score: 0.9333333333333333 

Classification Report:
               0          1          2  accuracy   macro avg  weighted avg
precision   1.0   0.875000   0.980000  0.933333    0.951667      0.938933
recall      1.0   0.984375   0.844828  0.933333    0.943068      0.933333
f1-score    1.0   0.926471   0.907407  0.933333    0.944626      0.932825
support    28.0  64.000000  58.000000  0.933333  150.000000    150.000000 

Confusion Matrix:
 [[28  0  0]
 [ 0 63  1]
 [ 0  9 49]] 



In [46]:
pred3 = tree_clf.predict(X_train_scaled)
clf_report = pd.DataFrame(classification_report(y_train, pred3, output_dict=True))
print("Train Result:\n")        
print("Accuracy Score:",accuracy_score(y_train, pred3),"\n")
print("Classification Report:\n",clf_report,"\n")
print("Confusion Matrix:\n",confusion_matrix(y_train, pred3),"\n")

Train Result:

Accuracy Score: 0.9776785714285714 

Classification Report:
                    0           1          2  accuracy   macro avg  \
precision   0.955556    0.975000   1.000000  0.977679    0.976852   
recall      1.000000    0.983193   0.951613  0.977679    0.978269   
f1-score    0.977273    0.979079   0.975207  0.977679    0.977186   
support    43.000000  119.000000  62.000000  0.977679  224.000000   

           weighted avg  
precision      0.978187  
recall         0.977679  
f1-score       0.977661  
support      224.000000   

Confusion Matrix:
 [[ 43   0   0]
 [  2 117   0]
 [  0   3  59]] 



**Although the accuracy went down the model is not overfit now.**

# Random Forest

In [47]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=300)
rf_clf.fit(X_train_scaled, y_train)

RandomForestClassifier(n_estimators=300)

In [48]:
print_score_details(rf_clf, X_train_scaled, y_train, X_test_scaled, y_test)

Test Result:

Accuracy Score: 0.9866666666666667 

Classification Report:
               0          1          2  accuracy   macro avg  weighted avg
precision   1.0   1.000000   0.966667  0.986667    0.988889      0.987111
recall      1.0   0.968750   1.000000  0.986667    0.989583      0.986667
f1-score    1.0   0.984127   0.983051  0.986667    0.989059      0.986674
support    28.0  64.000000  58.000000  0.986667  150.000000    150.000000 

Confusion Matrix:
 [[28  0  0]
 [ 0 62  2]
 [ 0  0 58]] 



In [49]:
predrf = rf_clf.predict(X_train_scaled)
clf_report = pd.DataFrame(classification_report(y_train, predrf, output_dict=True))
print("Train Result:\n")        
print("Accuracy Score:",accuracy_score(y_train, predrf),"\n")
print("Classification Report:\n",clf_report,"\n")
print("Confusion Matrix:\n",confusion_matrix(y_train, predrf),"\n")

Train Result:

Accuracy Score: 1.0 

Classification Report:
               0      1     2  accuracy  macro avg  weighted avg
precision   1.0    1.0   1.0       1.0        1.0           1.0
recall      1.0    1.0   1.0       1.0        1.0           1.0
f1-score    1.0    1.0   1.0       1.0        1.0           1.0
support    43.0  119.0  62.0       1.0      224.0         224.0 

Confusion Matrix:
 [[ 43   0   0]
 [  0 119   0]
 [  0   0  62]] 



**The model is overfit**

**Hyperparameter Tuning**

In [50]:
max_features = [5,7]
max_depth = [10,15,20,40]
min_samples_split = [10,30,40]
min_samples_leaf = [2, 10]
bootstrap = [True, False]

random_grid = {
    'max_features': max_features,
    'max_depth': max_depth, 
    'min_samples_split': min_samples_split,
    'min_samples_leaf': min_samples_leaf, 
    'bootstrap': bootstrap
}

rf_cv = RandomizedSearchCV(
    estimator=rf_clf, 
    scoring="f1",
    param_distributions=random_grid, 
    n_iter=20,
    cv=5, 
    
)

rf_cv.fit(X_train_scaled, y_train)
rf_best_params = rf_cv.best_params_
print("Best paramters: ",rf_best_params,"\n")

rf_clf = RandomForestClassifier(**rf_best_params)
rf_clf.fit(X_train_scaled, y_train)

print_score_details(rf_clf, X_train_scaled, y_train, X_test_scaled, y_test)

Best paramters:  {'min_samples_split': 30, 'min_samples_leaf': 10, 'max_features': 5, 'max_depth': 10, 'bootstrap': True} 

Test Result:

Accuracy Score: 0.98 

Classification Report:
               0          1          2  accuracy   macro avg  weighted avg
precision   1.0   0.984127   0.966102      0.98    0.983410      0.980120
recall      1.0   0.968750   0.982759      0.98    0.983836      0.980000
f1-score    1.0   0.976378   0.974359      0.98    0.983579      0.980007
support    28.0  64.000000  58.000000      0.98  150.000000    150.000000 

Confusion Matrix:
 [[28  0  0]
 [ 0 62  2]
 [ 0  1 57]] 



In [51]:
predrf = rf_clf.predict(X_train_scaled)
clf_report = pd.DataFrame(classification_report(y_train, predrf, output_dict=True))
print("Train Result:\n")        
print("Accuracy Score:",accuracy_score(y_train, predrf),"\n")
print("Classification Report:\n",clf_report,"\n")
print("Confusion Matrix:\n",confusion_matrix(y_train, predrf),"\n")

Train Result:

Accuracy Score: 0.9642857142857143 

Classification Report:
                    0           1          2  accuracy   macro avg  \
precision   0.953488    0.974359   0.953125  0.964286    0.960324   
recall      0.953488    0.957983   0.983871  0.964286    0.965114   
f1-score    0.953488    0.966102   0.968254  0.964286    0.962615   
support    43.000000  119.000000  62.000000  0.964286  224.000000   

           weighted avg  
precision      0.964475  
recall         0.964286  
f1-score       0.964276  
support      224.000000   

Confusion Matrix:
 [[ 41   2   0]
 [  2 114   3]
 [  0   1  61]] 



# K Nearest Neighbours

In [52]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors = 8)
knn_clf.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=8)

In [53]:
print_score_details(knn_clf, X_train_scaled, y_train, X_test_scaled, y_test)

Test Result:

Accuracy Score: 0.98 

Classification Report:
               0          1          2  accuracy   macro avg  weighted avg
precision   1.0   0.984127   0.966102      0.98    0.983410      0.980120
recall      1.0   0.968750   0.982759      0.98    0.983836      0.980000
f1-score    1.0   0.976378   0.974359      0.98    0.983579      0.980007
support    28.0  64.000000  58.000000      0.98  150.000000    150.000000 

Confusion Matrix:
 [[28  0  0]
 [ 0 62  2]
 [ 0  1 57]] 



In [54]:
predknn = knn_clf.predict(X_train_scaled)
clf_report = pd.DataFrame(classification_report(y_train, predknn, output_dict=True))
print("Train Result:\n")        
print("Accuracy Score:",accuracy_score(y_train, predknn),"\n")
print("Classification Report:\n",clf_report,"\n")
print("Confusion Matrix:\n",confusion_matrix(y_train, predknn),"\n")

Train Result:

Accuracy Score: 0.9285714285714286 

Classification Report:
                    0           1          2  accuracy   macro avg  \
precision   0.948718    0.932773   0.909091  0.928571    0.930194   
recall      0.860465    0.932773   0.967742  0.928571    0.920327   
f1-score    0.902439    0.932773   0.937500  0.928571    0.924237   
support    43.000000  119.000000  62.000000  0.928571  224.000000   

           weighted avg  
precision      0.929279  
recall         0.928571  
f1-score       0.928258  
support      224.000000   

Confusion Matrix:
 [[ 37   6   0]
 [  2 111   6]
 [  0   2  60]] 



**Although the Test accuracy is good the relatively high difference between the training and testing accuracy might be a sign I am underfitting the data.**

**Hyperparameter Tuning**

In [56]:

knn_grid = {
    "n_neighbors" : [5,7,8,9,11,13,15],
    "weights" : ['uniform','distance'],
    "metric" : ['minkowski','euclidean','manhattan']
}
knn_clf = KNeighborsClassifier()

knn_cv = GridSearchCV(
    knn_clf, 
    knn_grid,
    scoring="f1",
    cv=5
)

knn_cv.fit(X_train_scaled, y_train)
knn_best_params = knn_cv.best_params_
print("Best paramters: ",knn_best_params,"\n")
knn_clf = KNeighborsClassifier(**knn_best_params)
knn_clf.fit(X_train_scaled, y_train)
print_score_details(knn_clf, X_train_scaled, y_train, X_test_scaled, y_test)

Best paramters:  {'metric': 'minkowski', 'n_neighbors': 5, 'weights': 'uniform'} 

Test Result:

Accuracy Score: 0.9666666666666667 

Classification Report:
                    0          1          2  accuracy   macro avg  weighted avg
precision   0.965517   0.968254   0.965517  0.966667    0.966429      0.966685
recall      1.000000   0.953125   0.965517  0.966667    0.972881      0.966667
f1-score    0.982456   0.960630   0.965517  0.966667    0.969534      0.966594
support    28.000000  64.000000  58.000000  0.966667  150.000000    150.000000 

Confusion Matrix:
 [[28  0  0]
 [ 1 61  2]
 [ 0  2 56]] 



In [60]:
predknn = knn_clf.predict(X_train_scaled)
clf_report = pd.DataFrame(classification_report(y_train, predknn, output_dict=True))
print("Train Result:\n")        
print("Accuracy Score:",accuracy_score(y_train, predknn),"\n")
print("Classification Report:\n",clf_report,"\n")
print("Confusion Matrix:\n",confusion_matrix(y_train, predknn),"\n")

Train Result:

Accuracy Score: 0.9419642857142857 

Classification Report:
                    0           1          2  accuracy   macro avg  \
precision   0.906977    0.956897   0.938462  0.941964    0.934112   
recall      0.906977    0.932773   0.983871  0.941964    0.941207   
f1-score    0.906977    0.944681   0.960630  0.941964    0.937429   
support    43.000000  119.000000  62.000000  0.941964  224.000000   

           weighted avg  
precision      0.942211  
recall         0.941964  
f1-score       0.941857  
support      224.000000   

Confusion Matrix:
 [[ 39   4   0]
 [  4 111   4]
 [  0   1  61]] 



**This is better since the train and test accuracy are comparable.**

# Conclusion

XGBoost had the highest accuracy of 98.667 among the 4 models so it is best suited for this data.